[package]
name = "tjuaeui-realtime"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tjuaeui-api-types.workspace = true
axum.workspace = true
tokio.workspace = true
dashmap.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio-tungstenite.workspace = true
